### ISSUE TITLE
How to delete Auto-bumping using Milky Bumper (FREE)

### ISSUE THREAD

**Issue by KenKout** [Laiteux/Milky-Bumper#1]
Like my title, can you help me to delete it ? Thank you

**Comment by Laiteux** [comment]
Hi. What do you mean by that?

**Comment by KenKout** [comment]
How can I do it ? Im not good at coding

**Comment by KenKout** [comment]
Can you help me to edit it please ?

**Comment by Laiteux** [comment]
Install Visual Studio, clone this repo, edit whatever you want, build solution.

**Comment by KenKout** [comment]
Yes i know, but im bad at coding so can you help me please ?
