### ISSUE TITLE
The code is no longer works

### ISSUE THREAD

**Issue by KenKout** [Laiteux/Milky-Bumper#3]
![Untitled](https://user-images.githubusercontent.com/54569460/66564037-4d36e180-eb89-11e9-9867-6fd82d49f058.png)
Hi, it's have some problem, and I have enter correct cookie. Before few days, it was still working but atm it's not

**Comment by Laiteux** [comment]
Might be a Cloudflare UAM issue (didn't check), wait for them to disable it if so.

**Comment by KenKout** [comment]
Can you check it ?

**Comment by Laiteux** [comment]
No, I'm banned for now.

**Comment by KenKout** [comment]
Oh sad. Kk thank for your help
